language: node_js
sudo: false
node_js:
  - 9.5.0

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - yarn package
  - yarn lint
